package subcomponent

import (
	"math/rand"
)

type Params struct {
	InternalField int
}

type component struct {
	/*
		generate::components
		interfaceName::SubComponent
		config::.mockery.yml
		blackbox::true
	*/
	computedField int
	internalField int
}

func (p *Params) Convert() *component {
	return &component{
		computedField: 2 * p.InternalField,
		internalField: p.InternalField,
	}
}

// Code below was generated by components. DO NOT EDIT.
// Component version: v0.1.0

type SubComponent interface {
	Chance(s rand.Source) bool
}

func New(p Params) SubComponent {
	return p.Convert()
}
