package subcomponent_test

import (
	"testing"

	"github.com/flywingedai/components/example/subcomponent"
)

func initParams() subcomponent.Params {
	return subcomponent.Params{}
}

// Code below was generated by components. DO NOT EDIT.
// Component version: v0.1.0
type mocks struct {
	computedField int
	internalField int
}

func convert(p subcomponent.Params) *mocks {
	return &mocks{
		computedField: 2 * p.InternalField,
		internalField: p.InternalField,
	}
}

func buildMocks(t *testing.T) (subcomponent.SubComponent, *mocks) {
	params := initParams()

	return subcomponent.New(params), convert(params)
}
