package tests

import (
	"reflect"
)

var DefaultMockPriority = -20

/*
Function to automatically handle a mock chain. Use the autogenerated functions
from the components command placed at the bottom of your component definition
file, prefixed with "mock_" to use this.

ex. mock_component().$Method(args...).Return(response...) (or similar)

Has Priority = tests.DefaultMockPriority
*/
func (to *TestOptions[C, M, D]) Mock(
	mockChainFunction interface{},
) *TestOptions[C, M, D] {
	return to.copyAndAppend(DefaultMockPriority, func(state *TestState[C, M, D]) {

		/*
			TODO: No errors possible if the user only passes in the correct
			function via the generated mock_* functions. If not...
		*/
		function := reflect.ValueOf(mockChainFunction)

		if function.Kind() != reflect.Func {
			panic("invalid type " + function.Kind().String() + " passed to Mock()")
		}

		function.Call([]reflect.Value{reflect.ValueOf(state.Mocks)})
	})
}
